---

- name: lxc > profiles > Delete
  shell: |
    echo "Deleting profile ${LXC_PROFILE_ARG} ..."
    lxc profile delete "${LXC_PROFILE_ARG}" ${LXC_PROJECT_ARG}
  environment:
    LXC_PROFILE_ARG: "{{ lxc_cluster ~ ':' ~ lxc_profile.name }}"
    LXC_PROJECT_ARG: "{{ '--project ' ~ lxc_project }}"
  when: lxc_profile.name in lxc_profile_all
  with_items: "{{ lxc_profiles | default([]) }}"
  loop_control:
    loop_var: lxc_profile
